### ISSUE TITLE
Omni.exe  The process was terminated due to an unhandled exception.

### ISSUE THREAD

**Issue by pveliz** [ramon-mendes/SciterSharp#4]
Hi @ramon-mendes 

I downloaded Omni (http://misoftware.com.br/Omni) and I tried to run it but fails.
Here you have the Event Viewer log.

```Application: Omni.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.StreamWriter.CreateFile(System.String, Boolean, Boolean)
   at System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding, Int32, Boolean)
   at System.IO.File.InternalWriteAllText(System.String, System.String, System.Text.Encoding, Boolean)
   at Ion.IonApp..cctor()

Exception Info: System.TypeInitializationException
   at Ion.IonApp.GetStatus()
   at Omni.App.Setup()
   at Omni.Program.Main(System.String[])
```

```

Faulting application name: Omni.exe, version: 1.0.0.0, time stamp: 0x5c9a99b3
Faulting module name: KERNELBASE.dll, version: 10.0.17134.556, time stamp: 0xb9f4a0f1
Exception code: 0xe0434352
Fault offset: 0x000000000003a388
Faulting process id: 0x4bd8
Faulting application start time: 0x01d4e98c30f8f945
Faulting application path: C:\pveliz\SciterTools\OmniWin\Omni.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 57e23e0f-12f5-4f68-8b23-67d1b9b0253e
Faulting package full name: 
Faulting package-relative application ID: 
```
Let me know if you need more info.

Thanks

**Comment by ramon-mendes** [comment]
Problem indeed.
Fixed, Just download it again.
Thanks for reporting.
